index.jsx

This PR is due to fixing indicator.

Enable indicator for device selector

---

lib/actions/testActions.js
lib/components/ChannelView.jsx
lib/components/ChartView.jsx
lib/components/OtherSettingsView.jsx
lib/components/TimeoutView.jsx
lib/components/ToggleChannelModeView.jsx
lib/components/ToggleTestModeView.jsx
lib/components/TransmitSetupView.jsx
lib/containers/channelView.js
lib/containers/chartView.js
lib/containers/otherSettingsView.js
lib/containers/runTestView.js
lib/containers/timeoutView.js
lib/containers/toggleTestModeView.js
lib/containers/transmitSetupView.js
lib/reducers/testReducer.js
package.json

This PR simplifies the 3 test states to a simple bool as if the test is running or not to avoid mishaps losing UI control.

Simplified running state

---

lib/components/AppSidePanelView.jsx
lib/components/ChannelView.jsx
lib/components/OtherSettingsView.jsx
lib/components/PacketView.jsx
lib/components/TimeoutView.jsx
lib/components/TransmitSetupView.jsx
resources/css/index.scss

This PR is due to simplifying and shrinking the controls in the side panel.

Shrink side panel

---

lib/components/AppSidePanelView.jsx

This PR is due to removing packet type settings for receiver.

Remove packet type setting in receiver control view

---

package.json

This PR is due to update version.

Internal publish

---

index.jsx
lib/actions/testActions.js
lib/containers/runTestView.js

This PR is to support custom Direct Test Mode firmware.

Support custom firmware

---

Changelog.md
index.jsx
lib/actions/deviceActions.js
lib/actions/testActions.js
lib/containers/runTestView.js
lib/reducers/deviceReducer.js
package.json

This PR is to support custom firmware for nordic device. 
Test has been run on nRF52833

Enable custom firmware for nordic device

---

src/SidePanel/OtherSettingsView.jsx
src/SidePanel/PacketView.jsx
src/SidePanel/dropdown/Dropdown.scss
src/SidePanel/dropdown/Dropdown.tsx
src/SidePanel/dropdown/DropdownItem.tsx
src/SidePanel/dropdown/chevron.svg
src/SidePanel/dropdown/useDetectClick.ts

Task: https://trello.com/c/FmDrOJn6/19-implement-new-dropdown-component
- changed: chevron is rotated

Add dropdown button with new design

---

src/SidePanel/ChannelView.tsx

Signed-off-by: Pascal Pickel <Pascal.Pickel@nordicsemi.no>

fix: use channels instead of index

---

src/actions/testActions.ts

Use lambda to give logger correct context

---

Changelog.md
package-lock.json
package.json

Set release date and version

---

Changelog.md

Update release date and add entry

---

src/actions/testActions.ts

check if port is open before closing

---

Changelog.md
package.json
src/DeviceSelector.tsx

Signed-off-by: Pascal Pickel <Pascal.Pickel@nordicsemi.no>

fix: use correct casing for serialPort in deviceListing

---

README.md
azure-pipelines.yml

Update references to main

---

Changelog.md
README.md
package-lock.json
package.json
src/DeviceSelector.tsx
src/Receiver/ReceiverChartView.tsx
src/Receiver/index.tsx
src/Transmitter/TransmitterChartView.tsx
src/Transmitter/index.tsx
src/WarningView.tsx
src/actions/testActions.ts
src/utils/recoverHex.ts

Recover hex on rb protection

---

src/Receiver/index.tsx

Remove duplicate warning

---

src/index.tsx

feat: enable telemity

---

package.json

feat: update required engine version

---

Changelog.md

docs: update changelog and version

---

package.json

feat: update nrfutil to 2.0.3

---

package-lock.json
package.json

feat: update shared

---

package-lock.json
package.json

Fix: App can freeze when closing while waiting for usage data to send

---

.github/workflows/labels.yml

Add label check workflow

---

.github/workflows/labels.yml

ci: use shared labels workflow

---

Changelog.md
package.json

docs: v2.2.1 wasn't released yet

---

Changelog.md
package-lock.json
package.json

Release 2.3.0 prepare

---

Changelog.md

Fix: changelog

---

src/SidePanel/ChannelView.tsx

Revert: allow sweep values to be identical

---

package-lock.json
package.json

Fix: Make transmition handle ed of lisdr when on max index

---

doc/docs/index.md

Fixed link to nRF Connect for Desktop.
Reported on Teams.

doc: fix link to nRF Connect for Desktop

---

doc/zoomin/custom.properties

Updated the properties file with the missing `app`.

doc: zoomin: update properties

---

src/actions/testActions.ts

refactor: remove unused import

---

src/SidePanel/RunTestView.tsx
src/actions/testActions.ts

Fix: no need to dispacth endTest anyMore

---

src/actions/testActions.ts
src/dtm/DTM.ts

https://nordicsemi.atlassian.net/browse/NCD-1384

Free start stop button if device manually reset
